require_relative('models/customers.rb')
require_relative('models/films.rb')
require_relative('models/tickets.rb')

require('pry-byebug')

customer1 = Customer.new( {'name' => 'Oli', 'funds' => 50})
customer1.save()
customer2 = Customer.new( {'name' => 'Sinead', 'funds' => 75})
customer2.save()
customer3 = Customer.new( {'name' => 'Skye', 'funds' => 20})
customer3.save()

film1 = Film.new( {'title' => 'Logan', 'price' => 10})
film1.save()
film2 = Film.new( {'title' => 'Black Panther', 'price' => 10})
film2.save()
film3 = Film.new( {'title' => 'Meet The Feebles', 'price' => 2})
film3.save()
film4 = Film.new( {'title' => 'The Blues Brothers', 'price' => 3})
film4.save()
film5 = Film.new( {'title' => 'Last of the Mohicans', 'price' => 5})
film5.save()

ticket1 = Ticket.new('customer_id' => customer1.id, 'film_id' => film1.id)
ticket1.save()
ticket2 = Ticket.new('customer_id' => customer2.id, 'film_id' => film1.id)
ticket2.save()
ticket3 = Ticket.new('customer_id' => customer3.id, 'film_id' => film2.id)
ticket3.save()
ticket4 = Ticket.new('customer_id' => customer1.id, 'film_id' => film2.id)
ticket4.save()
ticket5 = Ticket.new('customer_id' => customer2.id, 'film_id' => film2.id)
ticket5.save()
ticket6 = Ticket.new('customer_id' => customer1.id, 'film_id' => film3.id)
ticket6.save()
ticket7 = Ticket.new('customer_id' => customer1.id, 'film_id' => film4.id)
ticket7.save()
ticket8 = Ticket.new('customer_id' => customer1.id, 'film_id' => film5.id)
ticket8.save()
ticket9 = Ticket.new('customer_id' => customer2.id, 'film_id' => film5.id)
ticket9.save()
ticket10 = Ticket.new('customer_id' => customer3.id, 'film_id' => film5.id)
ticket10.save()

binding.pry

nil
